repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace{% if cookiecutter.code_formatter == 'black' %}
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
        exclude: ^notebooks{% endif %}
